update dockerfile

diff --git a/applications/static-analysis/KaliX86-64/Dockerfile b/applications/static-analysis/KaliX86-64/Dockerfile
--- a/applications/static-analysis/KaliX86-64/Dockerfile
+++ b/applications/static-analysis/KaliX86-64/Dockerfile
@@ -16,11 +16,18 @@ RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 #avoid question/dialog during apt-get installs
 ARG DEBIAN_FRONTEND noninteractive
 
+#testing
+#RUN whoami
+#RUN ls -ld /tmp
+#RUN touch /tmp/testfile && echo "Successfully wrote to /tmp" || echo "Failed to write to /tmp"
+
+RUN chmod 1777 /tmp
+
 #add neccessary apt repository
 RUN apt update
 RUN apt install gnupg wget -y
-RUN wget -qO - https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc | apt-key add -
-RUN echo "deb https://ose-repo.syslog-ng.com/apt/ stable ubuntu-noble" | tee -a /etc/apt/sources.list.d/syslog-ng-ose.list
+RUN wget -qO - https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc | gpg --dearmor -o /etc/apt/keyrings/syslog-ng-ose.gpg;
+RUN echo "deb [signed-by=/etc/apt/keyrings/syslog-ng-ose.gpg] https://ose-repo.syslog-ng.com/apt/ stable ubuntu-noble" > /etc/apt/sources.list.d/syslog-ng-ose.list
 RUN apt update
 
 RUN apt install xauth -y
